# common parameters
row: 8
column: 10
layer: 4
verbose: true

# Mapping
parity_coverage: 8 # Each parity bit will have XOR of 8 data bits
parity_percent: .35
checksum_percent: .05
total_index_bit: 4
total_orientation_bit: 4
number_of_run: 100


# Encoding parameter
#redundancy: 50
encode_formatted_output: False  # Will print the origami as matrix instead of single line
# TODO: auto calculate the data_bit_per_origami
#data_bit_per_origami: 29


# Decoding parameter
save_ior: True # save individual origami information during decoding
maximum_error_to_fix: 8
correct_file: ''  # original encoded file. helps to check the status of the origami(decoded or not)
write_individual_origami_info: True
use_multi_core: False
parity_threshold: 2
data_threshold: 2
check_for_false_positive: 0

########  SIMULATION CONFIGURATION ##########
# most of the value will be a list. a random value from this list will be chosen during simulation
sim_file_size: [20, 2000, 40]  # start, end, gap
sim_rows: [8]
sim_cols: [10]
sim_layers: [3]
sim_parity_percent: [.35]
sim_checksum_percent: [.05]
sim_parity_coverage: [8]
sim_copies_of_each_origamies: 10
sim_fp_error_percent: 0  # false positive error percent
sim_average_error_dist: False
sim_maximum_number_of_error_checked_per_origami: 12
