# common parameters
row: 8
column: 10
layer: 8
verbose: true

# Mapping
parity_coverage: 8 # Each parity bit will have XOR of 8 data bits
parity_percent: .35
checksum_percent: .05
total_index_bit: 4
total_orientation_bit: 4
number_of_run: 100


# Encoding parameter
redundancy: 50
encode_formatted_output: False  # Will print the origami as matrix instead of single line
# TODO: auto calculate the data_bit_per_origami
#data_bit_per_origami: 29


# Decoding parameter
save_ior: True # save individual origami information during decoding
maximum_error_to_fix: 8
correct_file: ''  # original encoded file. helps to check the status of the origami(decoded or not)
write_individual_origami_info: True
use_multi_core: False
parity_threshold: 2
data_threshold: 2
check_for_false_positive: 0